### ISSUE TITLE
DCAT view fails on RDF format

### ISSUE THREAD

**Issue by asedgmen** [GeoscienceAustralia/ecat-ldapi#1]
http://13.54.73.187/ecat-ldapi/dataset/ga/103480?_view=dcat&_format=text/turtle

**Comment by nicholascar** [comment]
http://ldapi.ga.gov.au/ecat-ldapi/dataset/ga/116823?_view=dcat&_format=text/turtle works
http://ldapi.ga.gov.au/ecat-ldapi/dataset/ga/103620?_view=dcat&_format=text/turtle works

There appears to be no dataset eCatID 103480 in public eCat

**Comment by nicholascar** [comment]
Error message "There is no record with that eCat ID" returned now for instances like these
